env:
  global:
   - secure: "JyvGwUQQn56FZ+zl5vLPXuL9809KOqTJeWwl8P434tBlfzTq7yKv/5ZmwRJ/HJy8LfrndBcKM5rmhCtAgpqoX9HnA0Zjga1EU/tDJRrYLNsYiuNS39X0qY09mv2NE8Xj2Q9dnm6fHM9dyQBpROTv8/sXwuioyyG406vSBmLZc8k="
language: java
jdk:
  - openjdk7
  - oraclejdk7
script: ./travis.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d50931f8bba3694960c2
    on_success: change
    on_failure: always
  slack:
    secure: "bzzFEINdBZ3+p+5+Z7Rz5o7VvO91D0SWmzrGCEaXpOYp6iK1iDNIl8tb7b9XvT4j2J/8Mvu05dAyFg9VeQzdX9/Z+HG7dSIFmi7KcZFDtKOOhU01nhFwKLi4uos+tKD2nauhdTi1ui33MwnL0wgXSDoXlYUKlKF4eUmAFEP5IXg="
after_success:
  - coveralls
addons:
  coverity_scan:
    project:
      name: "go-lang-plugin-org/go-lang-idea-plugin"
    notification_email: "florinpatan@gmail.com"
    build_command_prepend: ""
    build_command:   "./coverity.sh"
    branch_pattern: coverity_scan
before_deploy: "./coverity.sh"
deploy:
  provider: releases
  api_key:
    secure: "cqMHnvEcNfwHwmy9FrtBADlmuYiu+EuUM3IveUOD7SX4oXNS4yZytcX2VfwECfCL92ZKG0vWswQCG8zTFWTPYBBmmU0SugktoSeZXTslSrezM/qmVyYp94AeVHL5tY0556ZTgRrSfRi+LxZFc+ZJg7Rj0xLMeyEwxtf4ftU5rLk="
  skip_cleanup: true
  file: ./google-go-language.jar
  on:
    tags: true
    all_branches: true
    jdk: oraclejdk7
